scan_filter_chain:
- name: shadows
  type: ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 170
    neighbors: 40
    window: 1
- name: dark_shadows
  type: LaserScanIntensityFilter
  params: 
    lower_threshold: 100
    upper_threshold: 10000
    disp_histogram: 0
- name: angular_bounds
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: -1.047
    upper_angle: 1.047
